from os import makedirs
from pathlib import Path

DATA_DIRECTORY = Path("data")
makedirs(DATA_DIRECTORY, exist_ok=True)

FIRST_XLSX_SHEET = "original problem"

FROM_BW_STRING = "Baden-Württemberger*in"

FIRST_INDEX_IN_XLSX = 1
NUMBER_OF_HEADER_COLUMNS = 1
NUMBER_OF_HEADER_ROWS = 1
FIRST_CONTENT_COLUMN_INDEX = FIRST_INDEX_IN_XLSX + NUMBER_OF_HEADER_COLUMNS
FIRST_CONTENT_ROW_INDEX = FIRST_INDEX_IN_XLSX + NUMBER_OF_HEADER_ROWS

COLUMN_WIDTH = 2.5  # guess

ALLOCATED_JULEI_COLOR = "BBFFBB"
FULL_SCHULUNG_COLOR = "FFBBBB"
ALLOCATION_COLOR = "00FF00"
WISH_FROM_BW_COLOR = "AA00FF"
WISH_NOT_FROM_BW_COLOR = "00AAFF"
